# Generated by Django 6.1 on 2026-09-16 19:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Relative weight when combining exams for term ranking', max_digits=5)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Sequence within the term')),
                ('counts_towards_midterm_rank', models.BooleanField(default=False)),
                ('counts_towards_endterm_rank', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exam_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fee_structures',
            },
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pathways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('school_type', models.CharField(choices=[('MIXED', 'Mixed'), ('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='MIXED', max_length=10)),
                ('knec_code', models.CharField(blank=True, max_length=30)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'streams',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'subject_groups',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='KES per month, e.g. 2000.00 - 50000.00', max_digits=10)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('max_classrooms_per_year', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('max_teachers', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Extra bullets for the pricing card, e.g. ["SMS notifications", "Priority support"]')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from Available Packages.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_packages',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('FINANCE', 'Finance Officer')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_login_at', models.DateTimeField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('password_reset_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='ClassroomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_promotions_done', to=settings.AUTH_USER_MODEL)),
                ('source_classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_record', to='api.classroom')),
                ('target_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_records', to='api.classroom')),
            ],
            options={
                'db_table': 'classroom_promotions',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='direct_messages_read', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direct_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('GRADUATED', 'Graduated'), ('TRANSFERRED_OUT', 'Transferred Out'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('subjects_locked_at', models.DateTimeField(blank=True, help_text="Timestamp of the student's first subject-selection submission. Once set, self-service edits are blocked until an admin unlocks it.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.classroom')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='api.enrollment')),
                ('pathway', models.ForeignKey(blank=True, help_text='CBC pathway chosen for this enrollment year, if the grade requires one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.pathway')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.feestructure')),
            ],
            options={
                'db_table': 'fee_structure_items',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('education_level', models.CharField(choices=[('JSS', 'Junior Secondary'), ('SSS', 'Senior Secondary'), ('LEGACY', 'Secondary (8-4-4)')], max_length=10)),
                ('level_order', models.PositiveSmallIntegerField(help_text='Sequence for promotion, e.g. Grade9=9, Grade10=10, Form1=101, Form2=102')),
                ('next_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grade', to='api.gradelevel')),
            ],
            options={
                'db_table': 'grade_levels',
                'ordering': ['curriculum_type', 'level_order'],
                'unique_together': {('name', 'curriculum_type')},
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='api.gradelevel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.gradelevel'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brought_forward', models.DecimalField(decimal_places=2, default=0, help_text='Balance carried in from previous terms. Positive=arrears, negative=credit.', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.enrollment')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.feestructure')),
            ],
            options={
                'db_table': 'invoices',
                'unique_together': {('enrollment', 'fee_structure')},
            },
        ),
        migrations.CreateModel(
            name='MpesaSTKPushRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_request_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('result_description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stk_requests', to='api.invoice')),
            ],
            options={
                'db_table': 'mpesa_stk_push_requests',
            },
        ),
        migrations.CreateModel(
            name='ParentGuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa code, bank slip no, etc.', max_length=60)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('order', models.PositiveSmallIntegerField(help_text='Sequence within the day: 1, 2, 3...')),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('ASSEMBLY', 'Assembly'), ('GAMES', 'Games / Sports'), ('PREP', 'Evening Prep / Study')], default='LESSON', max_length=10)),
                ('label', models.CharField(blank=True, help_text="'Period 1', 'Short Break', 'Lunch'", max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'period_slots',
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_subjects_passed', models.PositiveSmallIntegerField(default=0)),
                ('pass_mark_percentage', models.DecimalField(decimal_places=2, default=30, help_text='Percentage below which a subject is considered failed', max_digits=5)),
                ('grade_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rule', to='api.gradelevel')),
            ],
            options={
                'db_table': 'promotion_rules',
            },
        ),
        migrations.CreateModel(
            name='LicenseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], max_length=20)),
                ('limits_override', models.JSONField(blank=True, default=dict, help_text='Optional custom limits, e.g. {"max_students": 1200}. Overrides tier defaults.')),
                ('valid_months', models.PositiveIntegerField(default=12)),
                ('issued_by', models.CharField(help_text='Provider staff name/note', max_length=150)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Provider can deactivate an unused/leaked code.')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_tokens_redeemed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_tokens', to='api.school')),
            ],
            options={
                'db_table': 'license_tokens',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ISSUED', 'License Issued'), ('REDEEMED', 'Token Redeemed'), ('SUSPENDED', 'Suspended'), ('REINSTATED', 'Reinstated'), ('EXPIRED', 'Auto-Expired'), ('LIMIT_BLOCKED', 'Action Blocked by Limit')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_audit_logs', to='api.school')),
            ],
            options={
                'db_table': 'license_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], default='TRIAL', max_length=20)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('max_classrooms_per_year', models.PositiveIntegerField(blank=True, null=True)),
                ('max_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='api.school')),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='SelectionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_tracks', to='api.gradelevel')),
            ],
            options={
                'db_table': 'selection_tracks',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='selection_track',
            field=models.ForeignKey(blank=True, help_text='8-4-4 elective track chosen for this enrollment year (e.g. Technical+Humanities vs Triple Science).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.selectiontrack'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.stream'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('date_admitted', models.DateField(default=django.utils.timezone.now)),
                ('upi_number', models.CharField(blank=True, help_text='NEMIS/UPI number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian')], max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentguardianprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
            options={
                'db_table': 'parent_student_links',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.AddField(
            model_name='parentguardianprofile',
            name='students',
            field=models.ManyToManyField(related_name='guardians', through='api.ParentStudentLink', to='api.studentprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.studentprofile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.studentprofile'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Announcement'), ('EVENT', 'Event / Visiting Day'), ('CLOSING', 'School Closing'), ('FEE_REMINDER', 'Fee Balance Reminder'), ('ACADEMIC', 'Academic')], default='GENERAL', max_length=20)),
                ('audience_type', models.CharField(choices=[('ROLE', 'By Role'), ('GRADE', 'By Grade / Academic Year'), ('CLASSROOM', 'By Classroom'), ('INDIVIDUAL', 'Specific Students')], max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('include_students', models.BooleanField(default=True, help_text='Send to the students themselves.')),
                ('include_guardians', models.BooleanField(default=False, help_text="Also send to each student's parent/guardian.")),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.academicyear')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.classroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.gradelevel')),
                ('target_students', models.ManyToManyField(blank=True, related_name='communications_targeted', to='api.studentprofile')),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('has_papers', models.BooleanField(default=False, help_text='e.g. Mathematics PP1/PP2, English PP1/PP2/PP3')),
                ('pathway', models.ForeignKey(blank=True, help_text='Set only for CBC electives that belong to a pathway (STEM / Social Sciences / Arts & Sports Science). Leave blank for compulsory subjects and all 8-4-4 subjects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.pathway')),
                ('elective_group', models.ForeignKey(blank=True, help_text='Category (Technical/Humanities/Sciences) for grades that select subjects group-by-group, e.g. Form 3-4. Leave blank otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.subjectgroup')),
            ],
            options={
                'db_table': 'subjects',
                'unique_together': {('code', 'curriculum_type')},
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('grade_letter', models.CharField(max_length=10)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remark', models.CharField(blank=True, max_length=60)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='api.subject')),
            ],
            options={
                'db_table': 'grading_scales',
                'ordering': ['curriculum_type', '-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='api.subject')),
            ],
            options={
                'db_table': 'subject_papers',
                'ordering': ['subject', 'paper_number'],
                'unique_together': {('subject', 'paper_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectSelectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_pathway', models.BooleanField(default=False, help_text='If true, students at this grade must pick ONE pathway first, and their optional-subject choices must all belong to that pathway.')),
                ('min_optional_subjects', models.PositiveSmallIntegerField(default=0)),
                ('max_optional_subjects', models.PositiveSmallIntegerField(default=0)),
                ('min_total_subjects', models.PositiveSmallIntegerField(default=7)),
                ('max_total_subjects', models.PositiveSmallIntegerField(default=9)),
                ('grade_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rule', to='api.gradelevel')),
            ],
            options={
                'db_table': 'subject_selection_rules',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveSmallIntegerField(default=5, help_text='How many lesson periods/week this allocation needs.')),
                ('double_lesson', models.BooleanField(default=False, help_text='Schedule periods in consecutive pairs (e.g. double Maths) instead of singles.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_subject_allocations',
                'unique_together': {('teacher', 'subject', 'classroom', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.academicyear')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['academic_year__year', 'term_number'],
                'unique_together': {('academic_year', 'term_number')},
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='api.term'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.examtype')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.gradelevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.term')),
            ],
            options={
                'db_table': 'exams',
                'unique_together': {('term', 'exam_type', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Only meaningful for the IN_APP channel.')),
                ('personalized_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_recipients',
                'ordering': ['-communication__created_at'],
                'indexes': [models.Index(fields=['user', 'channel', 'is_read'], name='communicati_user_id_669407_idx')],
                'unique_together': {('communication', 'user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('BAD_PASSWORD', 'Bad Password'), ('UNKNOWN_USER', 'Unknown Username'), ('INVALID_FORMAT', 'Invalid Username Format'), ('ACCOUNT_LOCKED', 'Blocked - Account Locked'), ('OTP_SENT', 'OTP Sent'), ('OTP_SUCCESS', 'OTP Verified'), ('OTP_FAILED', 'OTP Incorrect/Expired')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_attempt_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='login_attem_user_id_7454df_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade_level', 'stream', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='api.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'db_table': 'student_subject_selections',
                'unique_together': {('enrollment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='api.gradelevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='api.subject')),
            ],
            options={
                'db_table': 'grade_subjects',
                'unique_together': {('grade_level', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='api.enrollment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subject')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subjectpaper')),
            ],
            options={
                'db_table': 'exam_results',
                'unique_together': {('exam', 'enrollment', 'subject', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructureMissingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_student_count', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_alerts', to='api.gradelevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_alerts', to='api.term')),
            ],
            options={
                'db_table': 'fee_structure_missing_alerts',
                'ordering': ['-last_checked_at'],
                'unique_together': {('grade_level', 'term')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('grade_level', 'term')},
        ),
        migrations.CreateModel(
            name='TermPositionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(choices=[('MIDTERM', 'Midterm Ranking'), ('ENDTERM', 'End of Term Ranking')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_position', models.PositiveIntegerField(blank=True, help_text='Rank across the whole grade (all streams)', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.term')),
            ],
            options={
                'db_table': 'term_position_rankings',
                'unique_together': {('term', 'enrollment', 'checkpoint')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double', models.BooleanField(default=False, help_text='Part of a double lesson pair with the following period slot.')),
                ('auto_generated', models.BooleanField(default=False, help_text='True if placed by the auto-generator; false if manually placed/edited.')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.teachersubjectallocation')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.classroom')),
                ('period_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.periodslot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.term')),
            ],
            options={
                'db_table': 'timetable_entries',
                'unique_together': {('classroom', 'period_slot', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TrackGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_choose', models.PositiveSmallIntegerField(default=1)),
                ('max_choose', models.PositiveSmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_rules', to='api.subjectgroup')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rules', to='api.selectiontrack')),
            ],
            options={
                'db_table': 'track_group_rules',
                'unique_together': {('track', 'group')},
            },
        ),
    ]
