# Generated by Django 6.1 on 2026-09-04 06:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Relative weight when combining exams for term ranking', max_digits=5)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Sequence within the term')),
                ('counts_towards_midterm_rank', models.BooleanField(default=False)),
                ('counts_towards_endterm_rank', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exam_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'fee_structures',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('school_type', models.CharField(choices=[('MIXED', 'Mixed'), ('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='MIXED', max_length=10)),
                ('knec_code', models.CharField(blank=True, max_length=30)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'streams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('FINANCE', 'Finance Officer')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('GRADUATED', 'Graduated'), ('TRANSFERRED_OUT', 'Transferred Out'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.classroom')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='api.enrollment')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.feestructure')),
            ],
            options={
                'db_table': 'fee_structure_items',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('education_level', models.CharField(choices=[('JSS', 'Junior Secondary'), ('SSS', 'Senior Secondary'), ('LEGACY', 'Secondary (8-4-4)')], max_length=10)),
                ('level_order', models.PositiveSmallIntegerField(help_text='Sequence for promotion, e.g. Grade9=9, Grade10=10, Form1=101, Form2=102')),
                ('next_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_grade', to='api.gradelevel')),
            ],
            options={
                'db_table': 'grade_levels',
                'ordering': ['curriculum_type', 'level_order'],
                'unique_together': {('name', 'curriculum_type')},
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='api.gradelevel'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.gradelevel'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.enrollment')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.feestructure')),
            ],
            options={
                'db_table': 'invoices',
                'unique_together': {('enrollment', 'fee_structure')},
            },
        ),
        migrations.CreateModel(
            name='ParentGuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_subjects_passed', models.PositiveSmallIntegerField(default=0)),
                ('pass_mark_percentage', models.DecimalField(decimal_places=2, default=30, help_text='Percentage below which a subject is considered failed', max_digits=5)),
                ('grade_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rule', to='api.gradelevel')),
            ],
            options={
                'db_table': 'promotion_rules',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.stream'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('date_admitted', models.DateField(default=django.utils.timezone.now)),
                ('upi_number', models.CharField(blank=True, help_text='NEMIS/UPI number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian')], max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parentguardianprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
            options={
                'db_table': 'parent_student_links',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.AddField(
            model_name='parentguardianprofile',
            name='students',
            field=models.ManyToManyField(related_name='guardians', through='api.ParentStudentLink', to='api.studentprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.studentprofile'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('has_papers', models.BooleanField(default=False, help_text='e.g. Mathematics PP1/PP2, English PP1/PP2/PP3')),
            ],
            options={
                'db_table': 'subjects',
                'unique_together': {('code', 'curriculum_type')},
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_type', models.CharField(choices=[('CBC', 'Competency Based Curriculum'), ('8-4-4', '8-4-4 (Legacy)')], max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('grade_letter', models.CharField(max_length=10)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('remark', models.CharField(blank=True, max_length=60)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='api.subject')),
            ],
            options={
                'db_table': 'grading_scales',
                'ordering': ['curriculum_type', '-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='api.subject')),
            ],
            options={
                'db_table': 'subject_papers',
                'ordering': ['subject', 'paper_number'],
                'unique_together': {('subject', 'paper_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectSelectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_optional_subjects', models.PositiveSmallIntegerField(default=0)),
                ('max_optional_subjects', models.PositiveSmallIntegerField(default=0)),
                ('min_total_subjects', models.PositiveSmallIntegerField(default=7)),
                ('max_total_subjects', models.PositiveSmallIntegerField(default=9)),
                ('grade_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_rule', to='api.gradelevel')),
            ],
            options={
                'db_table': 'subject_selection_rules',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.academicyear')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['academic_year__year', 'term_number'],
                'unique_together': {('academic_year', 'term_number')},
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='api.term'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.examtype')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.gradelevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.term')),
            ],
            options={
                'db_table': 'exams',
                'unique_together': {('term', 'exam_type', 'grade_level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade_level', 'stream', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to='api.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'db_table': 'student_subject_selections',
                'unique_together': {('enrollment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='api.gradelevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='api.subject')),
            ],
            options={
                'db_table': 'grade_subjects',
                'unique_together': {('grade_level', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='api.enrollment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subject')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subjectpaper')),
            ],
            options={
                'db_table': 'exam_results',
                'unique_together': {('exam', 'enrollment', 'subject', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_subject_allocations',
                'unique_together': {('teacher', 'subject', 'classroom', 'academic_year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('grade_level', 'term')},
        ),
        migrations.CreateModel(
            name='TermPositionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(choices=[('MIDTERM', 'Midterm Ranking'), ('ENDTERM', 'End of Term Ranking')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_position', models.PositiveIntegerField(blank=True, help_text='Rank across the whole grade (all streams)', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.term')),
            ],
            options={
                'db_table': 'term_position_rankings',
                'unique_together': {('term', 'enrollment', 'checkpoint')},
            },
        ),
    ]
