# Generated by Django 6.1 on 2026-09-05 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='brought_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance carried in from previous terms. Positive=arrears, negative=credit.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='M-Pesa code, bank slip no, etc.', max_length=60),
        ),
        migrations.CreateModel(
            name='MpesaSTKPushRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_request_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('result_description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stk_requests', to='api.invoice')),
            ],
            options={
                'db_table': 'mpesa_stk_push_requests',
            },
        ),
    ]
