# Generated by Django 6.1 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesastkpushrequest',
            name='is_general',
            field=models.BooleanField(default=False, help_text="True = pay the student's whole balance (split oldest-first) instead of one invoice."),
        ),
        migrations.AddField(
            model_name='mpesastkpushrequest',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
