# Generated by Django 6.1 on 2026-09-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoice_brought_forward_payment_receipt_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructureMissingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_student_count', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_alerts', to='api.gradelevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_alerts', to='api.term')),
            ],
            options={
                'db_table': 'fee_structure_missing_alerts',
                'ordering': ['-last_checked_at'],
                'unique_together': {('grade_level', 'term')},
            },
        ),
    ]
