# Generated by Django 6.1 on 2026-09-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Required (in addition to role=ADMIN) to delete students, classrooms, terms, academic years, grade levels, or subjects.'),
        ),
    ]
