# Generated by Django 6.1 on 2026-09-10 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feestructuremissingalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Announcement'), ('EVENT', 'Event / Visiting Day'), ('CLOSING', 'School Closing'), ('FEE_REMINDER', 'Fee Balance Reminder'), ('ACADEMIC', 'Academic')], default='GENERAL', max_length=20)),
                ('audience_type', models.CharField(choices=[('ROLE', 'By Role'), ('GRADE', 'By Grade / Academic Year'), ('CLASSROOM', 'By Classroom'), ('INDIVIDUAL', 'Specific Students')], max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('include_students', models.BooleanField(default=True, help_text='Send to the students themselves.')),
                ('include_guardians', models.BooleanField(default=False, help_text="Also send to each student's parent/guardian.")),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.academicyear')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.classroom')),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='api.gradelevel')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
                ('target_students', models.ManyToManyField(blank=True, related_name='communications_targeted', to='api.studentprofile')),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.studentprofile')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='direct_messages_read', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direct_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Only meaningful for the IN_APP channel.')),
                ('personalized_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='api.communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communication_recipients',
                'ordering': ['-communication__created_at'],
                'indexes': [models.Index(fields=['user', 'channel', 'is_read'], name='communicati_user_id_669407_idx')],
                'unique_together': {('communication', 'user', 'channel')},
            },
        ),
    ]
