# Generated by Django 6.1 on 2026-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_failed_login_attempts_user_last_failed_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectallocation',
            name='double_lesson',
            field=models.BooleanField(default=False, help_text='Schedule periods in consecutive pairs (e.g. double Maths) instead of singles.'),
        ),
        migrations.AddField(
            model_name='teachersubjectallocation',
            name='periods_per_week',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many lesson periods/week this allocation needs.'),
        ),
    ]
