# Generated by Django 6.1 on 2026-09-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teachersubjectallocation_double_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('order', models.PositiveSmallIntegerField(help_text='Sequence within the day: 1, 2, 3...')),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('ASSEMBLY', 'Assembly'), ('GAMES', 'Games / Prep')], default='LESSON', max_length=10)),
                ('label', models.CharField(blank=True, help_text="'Period 1', 'Short Break', 'Lunch'", max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'period_slots',
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double', models.BooleanField(default=False, help_text='Part of a double lesson pair with the following period slot.')),
                ('auto_generated', models.BooleanField(default=False, help_text='True if placed by the auto-generator; false if manually placed/edited.')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.teachersubjectallocation')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.classroom')),
                ('period_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.periodslot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.term')),
            ],
            options={
                'db_table': 'timetable_entries',
                'unique_together': {('classroom', 'period_slot', 'term')},
            },
        ),
    ]
