# Generated by Django 6.1 on 2026-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_periodslot_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodslot',
            name='slot_type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('ASSEMBLY', 'Assembly'), ('GAMES', 'Games / Sports'), ('PREP', 'Evening Prep / Study')], default='LESSON', max_length=10),
        ),
    ]
