# Generated by Django 6.1 on 2026-09-13 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_periodslot_slot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_promotions_done', to=settings.AUTH_USER_MODEL)),
                ('source_classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_record', to='api.classroom')),
                ('target_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_records', to='api.classroom')),
            ],
            options={
                'db_table': 'classroom_promotions',
            },
        ),
    ]
