# Generated by Django 6.1 on 2026-09-14 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_classroompromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], default='TRIAL', max_length=20)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('max_classrooms_per_year', models.PositiveIntegerField(blank=True, null=True)),
                ('max_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='api.school')),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ISSUED', 'License Issued'), ('REDEEMED', 'Token Redeemed'), ('SUSPENDED', 'Suspended'), ('REINSTATED', 'Reinstated'), ('EXPIRED', 'Auto-Expired'), ('LIMIT_BLOCKED', 'Action Blocked by Limit')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_audit_logs', to='api.school')),
            ],
            options={
                'db_table': 'license_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], max_length=20)),
                ('limits_override', models.JSONField(blank=True, default=dict, help_text='Optional custom limits, e.g. {"max_students": 1200}. Overrides tier defaults.')),
                ('valid_months', models.PositiveIntegerField(default=12)),
                ('issued_by', models.CharField(help_text='Provider staff name/note', max_length=150)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Provider can deactivate an unused/leaked code.')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_tokens_redeemed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_tokens', to='api.school')),
            ],
            options={
                'db_table': 'license_tokens',
                'ordering': ['-issued_at'],
            },
        ),
    ]
