# Generated by Django 6.1 on 2026-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_license_licenseauditlog_licensetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TRIAL', 'Free Trial'), ('GO', 'Go'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PRO', 'Pro (Unlimited)')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='KES per month, e.g. 2000.00 - 50000.00', max_digits=10)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('max_classrooms_per_year', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('max_teachers', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Extra bullets for the pricing card, e.g. ["SMS notifications", "Priority support"]')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from Available Packages.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_packages',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
    ]
